function model = ivmUpdateNuG(model, index)

% IVMUPDATENUG Update nu and g parameters associated with noise model.

% IVM
% /~[model.nu(index, :), model.g(index, :)] = ...
%     feval([model.noise.type 'NoiseUpdateParams'], ...
%           model.noise, model.mu, ...
%           model.varSigma, model.y, ...
% ~/          index);

[model.g(index, :), dlnZ_dvs] = feval([model.noise.type 'NoiseGradVals'], ...
                                      model.noise, ...
                                      model.mu(index, :), ...
                                      model.varSigma(index, :), ...
                                      model.y(index, :));

model.nu(index, :) = model.g(index, :).*model.g(index, :) - 2*dlnZ_dvs;
