function model = ivmUpdateNuG(model, index)

% IVMUPDATENUG Update nu and g parameters associated with noise model.

[model.nu(index, :), model.g(index, :)] = ...
    feval([model.noise.type 'NoiseUpdateParams'], ...
          model.noise, model.mu, ...
          model.varSigma, model.y, ...
          index);